spring:
  datasource:
    url: jdbc:h2:mem:stocks;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2-console
ingestion:
  vendorA:
    baseUrl: http://localhost:8081
  vendorB:
    csvPath: ./data/stock.csv
  sync:
    cron: "0 */1 * * * *"
springdoc:
  swagger-ui:
    path: /swagger-ui.html